# Azure Key Vault configuration
# Uncomment and set a valid endpoint of an Azure Key Vault like https://<your-keyvault-name>.vault.azure.net/
#quarkus.azure.keyvault.secret.endpoint=${KEY_VAULT_URI:}

# Application config
quarkus.application.name=azure-key-vault-secrets-quickstart
quarkus.application.version=1.0.0

# Log config
quarkus.log.level=INFO
quarkus.log.category."org.acme.keyvault".level=DEBUG